{% set name = "ipyflow-core" %}
{% set version = "0.0.186" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyflow-core-{{ version }}.tar.gz
  sha256: 4f61f6e1c58df7b2c1d6dc155f5e5cd5fe7cd1a263505c4bd11595a092a1bd02


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=48
    - wheel >=0.30.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.6
    - astunparse
    - black
    - ipykernel
    - ipython
    - ipywidgets
    - jupyter_client
    - nest-asyncio
    - pyccolo ==0.0.49
    - traitlets

test:
  # Disable test suite for now SDIST missing utils.py
  # source_files:
  #   - test
  imports:
    - ipyflow
  commands:
    - pip check
    # - pytest -vvv --capture=tee-sys test
  requires:
    - pip
    # - pytest

about:
  home: https://github.com/ipyflow/ipyflow
  dev_url: https://github.com/ipyflow/ipyflow/tree/master/core
  summary: Backend package for ipyflow's dataflow functionality
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
