{% set name = "ipyflow-core" %}
{% set version = "0.0.206" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bcf9dd6571665f504b7cfc20dca997048b529b570f783699d273bcaa8b688e16


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=48
    - wheel >=0.30.0
    - setuptools-git-versioning
    - pip
  run:
    - python >={{ python_min }}
    - astunparse
    - black
    - ipykernel
    - ipython
    - ipywidgets
    - jupyter_client
    - nest-asyncio
    - pyccolo ==0.0.68
    - traitlets
    - wheel >=0.30.0

test:
  imports:
    - ipyflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ipyflow/ipyflow
  dev_url: https://github.com/ipyflow/ipyflow/tree/master/core
  summary: Backend package for ipyflow's dataflow functionality
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
