schema_version: 1

context:
  name: ipyflow-core
  version: "0.0.225"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b04e9183a94d662dea9ce3c906d8bff60889d98411611c01227299fcaa8f612e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=48
    - wheel >=0.30.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }}
    - astunparse
    - black
    - ipykernel
    - ipython
    - ipywidgets
    - nest-asyncio
    - pyccolo ==0.0.80
    - traitlets

tests:
  - python:
      imports:
        - ipyflow
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: "Backend package for ipyflow's dataflow functionality"
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/ipyflow/ipyflow
  repository: https://github.com/ipyflow/ipyflow/tree/master/core

extra:
  recipe-maintainers:
    - thewchan
