schema_version: 1

context:
  name: ipyflow-core
  version: "0.0.228"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/2e/8a/cb57d1233f4f24cccfeb319808be493160ff7a10c2ab1791b5a630bc0450/ipyflow_core-${{ version }}.tar.gz
  sha256: 3d046ed47374e7fed7638fa56402d2d25a5376b306cccd0e36e8f05d19ccc44e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=48
    - wheel >=0.30.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }}
    - astunparse
    - black
    - ipykernel
    - ipython
    - ipywidgets
    - nest-asyncio
    - pyccolo ==0.0.83
    - traitlets

tests:
  - python:
      imports:
        - ipyflow
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: "Backend package for ipyflow's dataflow functionality"
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/ipyflow/ipyflow
  repository: https://github.com/ipyflow/ipyflow/tree/master/core

extra:
  recipe-maintainers:
    - thewchan
